name: Serverless Boilerplate Main Workflow

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Build
    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v4
      - run: cp .env.dist .env
      - run: npm ci
      - run: npm run lint
      - run: npm run test-coverage
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/

  sonarqube-analysis:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: coverage
        path: coverage/
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}